# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt .ui Files/detailsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_detailsDialog(object):
    
    def setData(self, discordPerson):
        self.lineEdit_username.setText(discordPerson.username)
        self.lineEdit_pbLink.setText(discordPerson.pbLink)
        self.lineEdit_discordId.setText(discordPerson.discordId)
    
    def okButtonPressed(self, detailsDialog):
        detailsDialog.close()
    
    def setupUi(self, detailsDialog):
        detailsDialog.setObjectName("detailsDialog")
        detailsDialog.resize(276, 173)
        # Label Username
        self.label_username = QtWidgets.QLabel(detailsDialog)
        self.label_username.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_username.setObjectName("label_username")
        
        # Label PB-Link
        self.label_pbLink = QtWidgets.QLabel(detailsDialog)
        self.label_pbLink.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_pbLink.setObjectName("label_pbLink")
        
        # Label Discord-ID
        self.label_discordId = QtWidgets.QLabel(detailsDialog)
        self.label_discordId.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_discordId.setObjectName("label_discordId")
        
        # lineEdit Username
        self.lineEdit_username = QtWidgets.QLineEdit(detailsDialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(10, 30, 113, 22))
        self.lineEdit_username.setReadOnly(True)
        self.lineEdit_username.setObjectName("lineEdit_username")
        
        # lineEdit PB-Link
        self.lineEdit_pbLink = QtWidgets.QLineEdit(detailsDialog)
        self.lineEdit_pbLink.setGeometry(QtCore.QRect(10, 80, 113, 22))
        self.lineEdit_pbLink.setReadOnly(True)
        self.lineEdit_pbLink.setObjectName("lineEdit_pbLink")
        
        # lineEdit Discord-ID
        self.lineEdit_discordId = QtWidgets.QLineEdit(detailsDialog)
        self.lineEdit_discordId.setGeometry(QtCore.QRect(10, 130, 113, 22))
        self.lineEdit_discordId.setReadOnly(True)
        self.lineEdit_discordId.setObjectName("lineEdit_discordId")
        
        # Button OK
        self.btn_ok = QtWidgets.QPushButton(detailsDialog)
        self.btn_ok.setGeometry(QtCore.QRect(180, 140, 93, 28))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_ok.clicked.connect(lambda: self.okButtonPressed(detailsDialog))

        self.retranslateUi(detailsDialog)
        QtCore.QMetaObject.connectSlotsByName(detailsDialog)

    def retranslateUi(self, detailsDialog):
        _translate = QtCore.QCoreApplication.translate
        detailsDialog.setWindowTitle(_translate("detailsDialog", "Details"))
        self.label_username.setText(_translate("detailsDialog", "Username: "))
        self.label_pbLink.setText(_translate("detailsDialog", "PB-Link:"))
        self.label_discordId.setText(_translate("detailsDialog", "Discord-ID:"))
        self.btn_ok.setText(_translate("detailsDialog", "OK"))