# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt .ui Files/newDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import requests

from DiscordPBYoinker import discordPBYoinker
from model import discordPerson

class Ui_newDialog(object):
    
    def getLink(self):
        self.discordId = self.lineEdit_discordId.text()
        try:
            self.pbLink, self.username = discordPBYoinker.getUrl(self.discordId)
            self.pbImage = QtGui.QImage()
            self.pbImage.loadFromData(requests.get(self.pbLink).content)
            self.pbPixmap = QtGui.QPixmap(self.pbImage)
            self.pbPixmap = self.pbPixmap.scaled(400, 400)
        except:
            print("PB-Link nicht herausgefunden.")
            self.pbLink = "https://img.freepik.com/free-vector/error-404-background_23-2148080813.jpg?size=338&ext=jpg"
            self.pbPixmap = QtGui.QPixmap("img/error.png")
            self.pbPixmap = self.pbPixmap.scaled(400, 400)
        
        self.label_img.setPixmap(self.pbPixmap)
        self.pbPixmap = self.pbPixmap.scaled(270, 270)
        self.btn_save.setEnabled(True)
    
    def saveButtonPressed(self, newDialog):
        self.discordUser = discordPerson.discordPerson(self.username, self.pbLink, self.discordId, self.pbPixmap)
        self.save = True
        self.fertig = True
        newDialog.close()
    
    def cancelButtonPressed(self, newDialog):
        self.save = False
        self.fertig = True
        newDialog.close()
    
    def setupUi(self, newDialog):
        newDialog.setObjectName("newDialog")
        newDialog.resize(541, 503)
        
        self.save = False
        self.fertig = False
        # DiscordPerson Variabeln xD
        self.discordId = "Default"
        self.pbLink = "Default"
        self.username = "Default"
        
        # Button Save
        self.btn_save = QtWidgets.QPushButton(newDialog)
        self.btn_save.setGeometry(QtCore.QRect(340, 470, 93, 28))
        self.btn_save.setObjectName("btn_save")
        self.btn_save.clicked.connect(lambda: self.saveButtonPressed(newDialog))
        self.btn_save.setEnabled(False)
        
        # Button Cancel
        self.btn_cancel = QtWidgets.QPushButton(newDialog)
        self.btn_cancel.setGeometry(QtCore.QRect(440, 470, 93, 28))
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_cancel.clicked.connect(lambda: self.cancelButtonPressed(newDialog))
        
        # Button Get PB-Link
        self.btn_getPBLink = QtWidgets.QPushButton(newDialog)
        self.btn_getPBLink.setGeometry(QtCore.QRect(240, 470, 93, 28))
        self.btn_getPBLink.setObjectName("btn_getPBLink")
        self.btn_getPBLink.clicked.connect(self.getLink)
        
        # Label Discord-ID
        self.label_discordId = QtWidgets.QLabel(newDialog)
        self.label_discordId.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_discordId.setObjectName("label_discordId")
        
        # lineEdit Discord-ID
        self.lineEdit_discordId = QtWidgets.QLineEdit(newDialog)
        self.lineEdit_discordId.setGeometry(QtCore.QRect(10, 30, 113, 22))
        self.lineEdit_discordId.setObjectName("lineEdit_discordId")
        self.label_img = QtWidgets.QLabel(newDialog)
        self.label_img.setGeometry(QtCore.QRect(20, 60, 400, 400))
        self.label_img.setObjectName("label_img")

        self.retranslateUi(newDialog)
        QtCore.QMetaObject.connectSlotsByName(newDialog)

    def retranslateUi(self, newDialog):
        _translate = QtCore.QCoreApplication.translate
        newDialog.setWindowTitle(_translate("newDialog", "New"))
        self.btn_save.setText(_translate("newDialog", "Save"))
        self.btn_cancel.setText(_translate("newDialog", "Cancel"))
        self.btn_getPBLink.setText(_translate("newDialog", "Get PB-Link"))
        self.label_discordId.setText(_translate("newDialog", "Discord-ID:"))
